services:
  bucstop:
    build:
      context: ./Bucstop WebApp/BucStop
      dockerfile: Dockerfile
    container_name: bucstop
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      # Disable HTTPS to avoid certificate issues
      - ASPNETCORE_HTTPS_PORT=
    depends_on:
      - api-gateway
    restart: unless-stopped

  api-gateway:
    build:
      context: ./Team-3-BucStop_APIGateway/APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_URLS=http://+:80
      # Disable HTTPS to avoid certificate issues
      - ASPNETCORE_HTTPS_PORT=
    depends_on:
      - snake
      - pong
      - tetris
    restart: unless-stopped

  snake:
    build:
      context: ./Team-3-BucStop_Snake/Snake
      dockerfile: Dockerfile
    container_name: game-snake
    ports:
      - "8082:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_URLS=http://+:80
      # Disable HTTPS to avoid certificate issues
      - ASPNETCORE_HTTPS_PORT=
    restart: unless-stopped

  pong:
    build:
      context: ./Team-3-BucStop_Pong/Pong
      dockerfile: Dockerfile
    container_name: game-pong
    ports:
      - "8083:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_URLS=http://+:80
      # Disable HTTPS to avoid certificate issues
      - ASPNETCORE_HTTPS_PORT=
    restart: unless-stopped

  tetris:
    build:
      context: ./Team-3-BucStop_Tetris/Tetris
      dockerfile: Dockerfile
    container_name: game-tetris
    ports:
      - "8084:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_URLS=http://+:80
      # Disable HTTPS to avoid certificate issues
      - ASPNETCORE_HTTPS_PORT=
    restart: unless-stopped

networks:
  bucstop-network:
    driver: bridge
