version: '3.4'
services:
  bucstop:
    build:
      context: /home/ubuntu/teststop/Bucstop\ WebApp/BucStop
      dockerfile: Dockerfile
    container_name: bucstop
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_HTTPS_PORT=
    volumes:
      - /home/ubuntu/teststop/webapp-environment-override.json:/app/appsettings.Production.json
    depends_on:
      - api-gateway
    restart: on-failure:3

  api-gateway:
    build:
      context: /home/ubuntu/teststop/Team-3-BucStop_APIGateway/APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=
    volumes:
      - /home/ubuntu/teststop/gateway-environment-override.json:/app/appsettings.Production.json
    depends_on:
      - snake
      - pong
      - tetris
    restart: on-failure:3

  snake:
    build:
      context: /home/ubuntu/teststop/Team-3-BucStop_Snake/Snake
      dockerfile: Dockerfile
    container_name: game-snake
    ports:
      - "8082:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=
    volumes:
      - /home/ubuntu/teststop/service-environment-override.json:/app/appsettings.Production.json
    restart: on-failure:3

  pong:
    build:
      context: /home/ubuntu/teststop/Team-3-BucStop_Pong/Pong
      dockerfile: Dockerfile
    container_name: game-pong
    ports:
      - "8083:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=
    volumes:
      - /home/ubuntu/teststop/service-environment-override.json:/app/appsettings.Production.json
    restart: on-failure:3

  tetris:
    build:
      context: /home/ubuntu/teststop/Team-3-BucStop_Tetris/Tetris
      dockerfile: Dockerfile
    container_name: game-tetris
    ports:
      - "8084:80"
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=
    volumes:
      - /home/ubuntu/teststop/service-environment-override.json:/app/appsettings.Production.json
    restart: on-failure:3

networks:
  bucstop-network:
    driver: bridge
